### ISSUE TITLE
split re-usable code from `main.rs` to a library `lib.rs`

### ISSUE THREAD

**Issue by AucaCoyan** [jntrnr/new-nu-parser#3]
Hi! I was testing this small parser in `nufmt` but I found it is still a single executable that does it all.
I will do a PR to split it so I can add as a dependency in another project 😄 

brb!

**Comment by sholderbach** [comment]
First step done by #4

**Comment by AucaCoyan** [comment]
I think #4 resolves this issue, do you have any feature request @sholderbach? 
I'd be delighted to deliver!

**Comment by sholderbach** [comment]
I set myself a little separate function for testing that does mostly what `main.rs` does up in [`e35c856` (#5)](https://github.com/jntrnr/new-nu-parser/pull/5/commits/e35c85685fd38c69862350adb96d8948f1d9c290). Don't have any special requests.

Happy to have you hacking here as well!
Feel free to close this.
